### ISSUE TITLE
<script th:src="@{/webjars/jquery/2.1.1/jquery.min.js}"/> generate wrong html code

### ISSUE THREAD

**Issue by Kevin-Ling** [thymeleaf/thymeleaf#719] opened 2018-10-24 01:10 UTC
I'm using 3.0.9 thymeleaf via springboot 2.0.4

when try to generate the following page:

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body>

<h1>Spring Boot - Multiple file upload example - AJAX</h1>

<form method="POST" enctype="multipart/form-data" id="fileUploadForm">
    <input type="text" name="extraField"/><br/><br/>
    <input type="file" name="files"/><br/><br/>
    <input type="file" name="files"/><br/><br/>
    <input type="submit" value="Submit" id="btnSubmit"/>
</form>

<h1>Ajax Post Result</h1>
<pre>
    <span id="result"></span>
</pre>

<script th:src="@{/webjars/jquery/2.1.1/jquery.min.js}"/>
<script th:src="@{/js/main.js}"/>

</body>
</html>
```

the first <script> tag was not processed properly it will wrongly include the following page content like: 

```
<script src="/webjars/jquery/2.1.1/jquery.min.js">  
    <script src="/js/main.js"></script>
    </body>
    </html>
</script>
```

workaround is to wirte script tags like this

```
<script th:src="@{/webjars/jquery/2.1.1/jquery.min.js}"></script>
<script th:src="@{/js/main.js}"></script>
```

**Comment by neVERberleRfellerER** [comment] 2018-10-26 09:17
Do you see incorrect HTML directly in source or in developer tools? Because your incorrect output is exactly what parse tree from empty script tags looks like, because HTML does not allow empty script tags. And transforming this in Thymeleaf is probably bad idea so in case you get incorrect HTML in developer tools only and not in raw generated HTML, this is not a bug in Thymeleaf.
Also, it generates exactly what it should in my test.

**Comment by danielfernandez** [comment] 2018-10-26 23:54
Exactly. @neVERberleRfellerER is right. HTML5 does not allow void or self-closing `<script>` elements, so your `<script ... />` are interpreted by HTML5 parsers (like the one in your browser) exactly the same as an open tag `<script ...>`. That's why you see the first script including the rest of the page, most probably from a browser or some dev tools applying a parser.

So this:
```html
<script th:src="@{/webjars/jquery/2.1.1/jquery.min.js}"></script>
<script th:src="@{/js/main.js}"></script>
```
…is not actually a _workaround_, but the correct way to write those empty `script` tags in HTML5.

**Closed as completed by danielfernandez** 2018-10-26 23:54 UTC
Labels: tracker:question, status:answered
