### ISSUE TITLE
Processors implementing an AbstractModelVariableProcessor without replacing the tag throw a StackOverflowException

### ISSUE THREAD

**Issue by phillipuniverse** [thymeleaf/thymeleaf#518] opened 2016-07-18 20:36 UTC
1. Add a new processor to the dialect that extends from `AbstractModelVariableProcessor` with no implementation in the `process()` method:

``` java
public class FormProcessor extends AbstractElementModelProcessor {


    public FormProcessor() {
        super(TemplateMode.HTML,
            "blc",
            "form",
            true,
            null,
            false,
            1);
    }

    /* (non-Javadoc)
     * @see org.thymeleaf.processor.element.AbstractElementModelProcessor#doProcess(org.thymeleaf.context.ITemplateContext, org.thymeleaf.model.IModel, org.thymeleaf.processor.element.IElementModelStructureHandler)
     */
    @Override
    protected void doProcess(ITemplateContext context, IModel model, IElementModelStructureHandler structureHandler) {
        // intentionally unimplemented
    }

}
```
1. This operates off of a template like this one:

``` html
<blc:form method="POST">

</blc:form>
```
1. This throws the following exception:

```
java.lang.StackOverflowError
    org.thymeleaf.engine.TemplateModelController.skipBody(TemplateModelController.java:297)
    org.thymeleaf.engine.TemplateModelController.increaseModelLevel(TemplateModelController.java:321)
    org.thymeleaf.engine.TemplateModelController.shouldProcessOpenElement(TemplateModelController.java:419)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1236)
    org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.Model.process(Model.java:290)
    org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1620)
    org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1567)
    org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.Model.process(Model.java:290)
    org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1620)
    org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1567)
    org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.Model.process(Model.java:290)
    org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1620)
    org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1567)
    org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
    org.thymeleaf.engine.Model.process(Model.java:282)
    org.thymeleaf.engine.Model.process(Model.java:290)
    org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
    org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1620)
    org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
    org.thymeleaf.engine.Model.process(Model.java:282)
...
```

From what I can see in tracing through the code, the model processors are supposed to be applied in 2 steps: the 1st step is to compile the model from the body of the tag, and then the 2nd step should actually operate off of the tag with the built model from the body. The problem is that it does this over and over and doesn't stop. It's like it does step 2 (the process the tag) and then forgets that it already covered that model and tries to execute it again.

The fix in my case is to replace the `<blc:form>` tag with really anything else, like `<form>` (which is how it's designed to work; see http://forum.thymeleaf.org/Thymeleaf-3-Upgrade-Tag-name-replacement-td4029842.html#a4029843). But, if my final goal was to not replace the tag (like if I wanted a processor to operate off of an HTML element itself) with something then I would be in trouble.

**Comment by danielfernandez** [comment] 2016-07-18 22:56
Should be fixed now. The problem was that a recompute of the `ProcessorElementIterator` was being forced even when the `ModelProcessor` made absolutely no changes on the `tag`.

This recompute should only take place if the tag has suffered any changes. That is what allows processors to trigger the execution of new processors on tags –processors that wouldn't be initially applicable given the original state of markup at the template– by making changes on the markup in processing time (there is an entire class devoted to keeping the accounts of what processors match, which have already been executed, which haven't... `ProcessorElementIterator`).

Note however that if these _no-op_ processor was followed in execution by another processor that did change the tag but didn't rename it, the _no-op_ processor would be executed again (because that would force a recompute of the _applicable_ processors, and this no-op would be applicable again). This is by design, and in fact needed in some parts of the Standard Dialect.

**Closed as completed** 2016-07-18 22:56 UTC
Labels: tracker:problem, status:solved

**Comment by danielfernandez** [comment] 2016-07-18 22:58
Already in `3.0.1-SNAPSHOT`
