### ISSUE TITLE
Exceptions in inline expressions are silently ignored

### ISSUE THREAD

**Issue by mus65** [thymeleaf/thymeleaf#354] opened 2015-03-13 07:53 UTC
When an inline expression causes an exception, it is silently ignored and Thymeleaf just continues processing the rest of file:

e.g.
`<div>[[${null.toUpperCase()}]]</div>`

will not cause an exception, but Thymeleaf will simply output the expression as is and continue. If I use th:text instead, Thymeleaf will properly throw an exception and cause an Internal Server Error.

This makes debugging really annoying, especially since I'm doing a lot of inlining and honestly not using the "natural template" feature at all (for one thing because it doesn't work that well with the layout dialect anyway and because I have to localize everything and using something like `<span th:text="#{text}">Text</span>` duplicates strings in the HTML template and the message bundle).

This is with Spring Boot 1.2.1 and Thymeleaf 2.1.4.

**Comment by danielfernandez** [comment] 2015-11-22 01:07
If text inlining is active (Thymeleaf 2.1), this shouldn't happen, and actually cannot be reproduced.

I've just added this test with your scenario (adding `th:inline="text"`), and it passes alright: https://github.com/thymeleaf/thymeleaf-tests/blob/2.1-spring41/src/test/resources/templateengine/attrprocessors/inline/inline22.thtest

Thymeleaf 3.0 has also been checked (though 3.0 does not require `th:inline="text"`), and it also works alright.

Closing this for now.

**Comment by danielfernandez** [comment] 2015-11-22 01:30
Reopening. This can be reproduced in 2.1 using SpringEL (_SpringStandard_ dialect), but not OGNL (_Standard_ dialect). So there is a lack of synchronization between those two scenarios.

Actually, outputting the inlined expression seems to be the expected result in order to cover non-parsable expressions (not execution exceptions), but `OgnlVariableExpressionEvaluator` only catches `OgnlException` and, in the example, the raised exception is `NullPointerException`.

In 3.0 an exception is raised, either using Spring or not.

**Comment by danielfernandez** [comment] 2015-11-22 01:56
Fixed now. Behaviour in 2.1 now matches that of 3.0 both with and without Spring integration. An exception should always be thrown when an inlined expression fails.

This is already in `2.1.5-SNAPSHOT`

**Closed as completed by danielfernandez** 2015-11-22 01:56 UTC
Labels: tracker:problem, status:solved
