### ISSUE TITLE
Update Thymeleaf to support the latest OGNL

### ISSUE THREAD

**Issue by rhues** [thymeleaf/thymeleaf#727] opened 2018-12-11 02:29 UTC
I'm using thymeleaf 3.0.11, OGNL 3.1.12, attoparser 2.0.5, unbescape 1.1.6 and this works fine.

However, Thymeleaf does not seem to support the latest OGNL, which is 3.2.8. When trying this, the resulting error message is:

"java.lang.RuntimeException: MemberAccess implementation must be provided!"

I request support for the latest OGNL.

**Comment by danielfernandez** [comment] 2019-04-02 22:12
I'm moving this to the _feature_ tracker as that's the consideration I believe a dependency update such as this should have unless there were any CVEs affecting the version of OGNL we are using in the way we are using it…

**Comment by deved65** [comment] 2019-09-24 05:08
The problem is, that with the 3.2.x branch of OGNL the constructor of OGNLContext that is used by Thymeleaf in line 315 of OGNLVariableExpressionEvaluator has become deprecated. But unfortunately it is not only deprecated but also not working anymore as it will always throw a RuntimeException subsequently which down the chain ends up in Thymeleaf's exception handling. This def. requires a software change either with Thymeleaf or with OGNL. Please compare to: jkuhnert/ognl#81.

**Comment by lukaszlenart** [comment] 2019-09-26 10:33
Does Thymeleaf provide its own `MemberAccess` implementation?

**Comment by deved65** [comment] 2019-09-28 04:33
I'm not expert on the thymeleaf code base. But I cloned the thymeleaf/thymeleaf repo and checked for implementations of MemberAccess. I could not find any implementation.

**Comment by lukaszlenart** [comment] 2019-10-01 08:54
Ok, so when you want to use OGNL 3.2.x you should provide your own implementation of `MemeberAccess` - it can be even the [default one](https://github.com/jkuhnert/ognl/blob/master/src/test/java/ognl/DefaultMemberAccess.java) - you can copy it into your code

**Comment by lukaszlenart** [comment] 2019-10-03 06:09
Also please be aware that 3.2.x line is still a [work-in-progress](https://github.com/jkuhnert/ognl/blob/master/docs/VersionNotes.md#release-notes---version-323---wip-new-changes-are-coming) - maybe I should express that better

**Comment by danielfernandez** [comment] 2020-11-16 22:53
OGNL dependency updated to 3.1.26 by means of 2da733d.

OGNL 3.2.x requires Java 7, but Thymeleaf 3.0's current Java compability is set to Java 6. So 3.1.26 is the newest version of OGNL that can be used.

**Closed as completed by danielfernandez** 2020-11-16 22:53 UTC
Labels: tracker:feature, status:insnapshot
