### ISSUE TITLE
Thymeleaf not replacing internationalized text

### ISSUE THREAD

**Issue by suhasbhatta** [thymeleaf/thymeleaf#644] opened 2017-09-29 12:43 UTC
`th:text="#{{{ngDialogData.title}}}"` does not replace the text instead prints ```
`??Error !!_en_US??
??upload_en_US??`

Error !! and upload has a value in messages.properties file. 

the above html code is calling from ngDialog and it replacecs {{ngDialogData.title}} with the data passed from ngDialog function.

Please let me know if you need any more information

**Comment by danielfernandez** [comment] 2017-09-29 12:54
Is `{{ngDialogData.title}}` an Angular placeholder, resolved at the browser side? Please take into account that Thymeleaf works at the server side, so it executes before your HTML (including the Angular placeholder) is sent to the browser.

In any case, note `#{...}` Thymeleaf expressions work against the message externalization (or i18n if you prefer) mechanism that has been configured by the environment. If this is a Spring application, your Spring `MessageSource` should be able to access a `.properties` file containing an entry for each of the keys specified inside `#{...}`. These keys have to be single-valued, and their name has to adhere to specific naming conventions.

**Comment by danielfernandez** [comment] 2017-10-02 21:29
I'm closing this as the issue is a mix between client-side and server-side concepts. Thymeleaf is rendering your texts as `??{{ngDialogData.title}}_en_US??` at the server side, and later Angular is replacing your `{{ngDialogData.title}}` placeholders there, giving you the impression that internationalization is not working.

**Closed as completed** 2017-10-02 21:29 UTC
Labels: tracker:question, status:answered

**Comment by suhasbhatta** [comment] 2017-10-03 09:48
Yes got it now. It is my bad to post the question is that. But is there any work around for the same, passing the data from the client side and rendering the html once the client is rendered?
