### ISSUE TITLE
How to add values in Thymeleaf variable in the loop and after complete loop display final value

### ISSUE THREAD

**Issue by knavadiya** [thymeleaf/thymeleaf#667] opened 2018-02-01 06:06 UTC
**I am design bill for products, I want to display all products in thymeleaf template using table and at last, out of loop I want to display sum of price of all products in thymeleaf. how can I define global variable and do it ?**

```

<table th:with="totalPrice=0">
                <tr th:each="count,iterator: ${product.paidService}">
                    <td th:text="${iterator.index+1}"></td>
                    <td th:text="${count.name}"></td>
                    <td>Paid</td>
                    <td th:text="${count.price}"></td>  
                    <p th:with="totalPrice=${totalPrice + count.price}"> </p>           
                </tr>

        <span th:text="${totalPrice}"></span>
</table>
```
I am geeting 0 as output but I want sum of all products price as output

How to make variable global and solve my problem

**Comment by ultraq** [comment] 2018-02-03 01:20
Closing as this is a duplicate of https://github.com/thymeleaf/thymeleaf/issues/666#issuecomment-362168531 and being answered over in that issue.

**Closed as completed by ultraq** 2018-02-03 01:20 UTC
Labels: tracker:question, status:answered
