### ISSUE TITLE
Incompatible behaviour th:remove and th:inline

### ISSUE THREAD

**Issue by sis-yoshiday** [thymeleaf/thymeleaf#566] opened 2017-01-19 11:18 UTC
Hi.
I found two incompatible behaviour in the cource of migrating thymeleaf version from 2.1.5 to 3.0.3 

## 1.  th:remove="all-but-first"

```html
<ul th:remove="all-but-first">
  <li th:each="item : ${items}" th:text="${item}">item1, should not be shown</li>
  <li>item2, should not be shown</li>
  <li>item3, should not be shown</li>
</ul>
```

When passing empty List to above template, rendered html like below, 

### thymeleaf 2.1.5
```html
<ul>
</ul>
```

### thymeleaf 3.0.3
```html
<ul>
  <li>item2, should not be shown</li>
</ul>
```

## 2. variable in th:inline="javascript"

```html
<script type="text/javascript" th:inline="javascript">
  <!--*/ wrong comment syntax /*-->
  var v = /*[[${message}]]*/'this should not be shown';
</script>
<script type="text/javascript" th:inline="javascript">
  <!--/* correct comment syntax */-->
  var v = /*[[${message}]]*/'this should not be shown';
</script>
```

### thymeleaf 2.1.5
```html
<script type="text/javascript">
  <!--*/ wrong comment syntax /*-->
  var v = 'real message';
</script>
<script type="text/javascript">
  var v = 'real message';
</script>
```

### thymeleaf 3.0.3
```html
<script type="text/javascript">
  <!--*/ wrong comment syntax /*-->
  var v = /*"real message"*/'this should not be shown';
</script>
<script type="text/javascript">
  var v = "real message";
</script>
```

### bug or specification ?
I can't to decide if these behaviour is .

#### reproduction code
https://github.com/sis-yoshiday/thymeleaf-migration-issues

#### related post (forum)
http://forum.thymeleaf.org/strange-behaviour-of-th-remove-quot-all-but-first-quot-td4030187.html

I love Thymeleaf, thanks.

**Comment by danielfernandez** [comment] 2017-01-19 23:29
Thanks a lot for your comments.

As for the first item, the `all-but-first` behaviour, it is clearly a bug. I've filed if separately here: #567 

As for the second item, it is actually expected behaviour given the improved textual parsing being applied on JavaScript fragments. HTML comment prefixes/suffixes inside a JavaScript fragment should be ignored (it wasn't possible before in 2.1), and so there is a JavaScript comment with this content:

```
/*-->\n  var v = /*[[${message}]]*/
```
The whole of the comment content is not parseable as an *inlined output expression*, so the behaviour of executing, outputting and then removing everything until the end of line does not apply. But `[[${message}]]` inside that comment is a valid inlined output expression, so it is executed alright and transformed into `"real message"`. Thus the different behaviour with 2.1.5.

As for the double quotes being used now... it's actually a consequence of the adoption of Jackson, which uses them for JSON/JS object serialisation. Also, it is in accordance with what seems to be becoming a semi-standard now in the JS world.

I'm closing this ticket for now given I've already filed a specific one for the bug, but please feel free to reopen it should any more issues or questions arise.

**Closed as completed by danielfernandez** 2017-01-19 23:29 UTC
Labels: tracker:question, status:answered
