### ISSUE TITLE
intermittent issue with th:inline="javascript" 

### ISSUE THREAD

**Issue by kiriljames** [thymeleaf/thymeleaf#597] opened 2017-04-13 04:29 UTC
I've been encountering this issue sometimes when I reload the page. 
It seems like there is problem with parsing inline javascript.

The following code:

    <script type="text/javascript" th:inline="javascript">
        /*<![CDATA[*/
           var all =  /*[[ ${currencyAll} ]]*/;
           var filterCd1 =  /*[[ ${filterCd1} ]]*/;
           var filterCd2 =  /*[[ ${filterCd2} ]]*/;
        /*]]>*/
    </script>

produces the following wrong output:

    <script type="text/javascript">
      /*<![CDATA[*/
        var all =  "ALL"

the next remaining line of codes after that are missing and the page will not be rendered.

I thought this is the same issue reported in #563 and waited for the fix to be released.
I tried using the latest version (3.0.5) when it was released and still the issue would still occur.

**Comment by danielfernandez** [comment] 2017-04-13 21:55
Your code as such is correctly processed for me (actually, its structure corresponds with an amount of tests at our testing repository). Also, #563 was related with large buffer sizes at the JavaScript text parser, but your script is very small for this to be the same issue. So we will need to dig deeper into this:

1. What do you mean with this problem appearing when *reloading*? Do you mean that the first time you process this template it is correctly processed, but then you process it again and this happens?

2. Is your template cache active?

3. Does this still happen if you move this piece of code to a different part of the HTML? Or does this happen *in the same way*?

4. Does this behaviour also happens to you if you access this URL using `curl` or `wget` from the command line, instead of a browser?

**Comment by kiriljames** [comment] 2017-04-14 02:55
1. This happens when we try to reload or redirect into the page. There is instance that it will happen the first time the template is processed but most of the time when reloading the page (reload and reload until the issue will occur). I could not find constant basis on when the issue would occur.


2. Yes the template is cacheable since the default is true.

   The following is my bean configuration.

        <bean id="templateResolver" class="org.thymeleaf.spring4.templateresolver.SpringResourceTemplateResolver">
            <property name="prefix" value="/WEB-INF/html/" />
            <property name="suffix" value=".html" />
            <property name="templateMode" value="HTML" />
            <property name="order" value="0" />
            <property name="characterEncoding" value="UTF-8" />
        </bean>

    I've tried adding  `<property name="cacheable" value="false"></property>` but still happens.	

3. The script is located inside the fragment and was placed at the bottom.
   I tried moving it to the top but still the same.
   I also tried removing the entire code out of the fragment but the issue would still occur in the next inline javascript in html so I concluded it will happen to all inlined javascript.
   
   I have tried another approach which I removed the `th:inline="javascript"` syntax.
   
        <script type="text/javascript">
            var all = "[[${currencyAll}]]";
            var filterCd1 = "[[${filterCd1}]]";
            var filterCd2 = "[[${filterCd2}]]";
       </script>
   
   this however gives us the values we need without the issue occurring. This would have been a good workaround but this does't work for objects sadly :(.
   
   I also tried creating a very simple html file and included only one fragment (no more than 150 LOC including the fragment) which contains the inline javascript and no problem at all. So I think there might be a factor to be considered in processing a large html files and in processing an inliine javascript which contains `[[ ${...} ]]` and `[[ #{.. } ]]`
   
4. No, I haven't tried using `curl `or `wget `command when accessing the URL.

**Comment by danielfernandez** [comment] 2017-04-14 08:55
OK thanks. The fact that this doesn't happen always makes me doubt a bit about this being an issue at the Thymeleaf side, but anyway it still could be a matter of some interaction I'm still not thinking of. 

Would it be possible for you to send me the complete HTML template that's causing this, or at least a test template with an equivalent structure that reproduces this issue for you? 

Also, testing from outside the browser would help if you can. 

And another question: when this happens, is only the script that is cut or you are not receiving any additional markup *at all*, not even the `</script>` closing tag or any more tags after that?

**Comment by kiriljames** [comment] 2017-04-14 09:40
I'm still trying to reproduce the issue using curl command. But as of the moment, I haven't replicated it yet.

Based on the response from server, there is no additional markup at all not even the `</script>` closing tag.

![img_14042017_183402_0](https://cloud.githubusercontent.com/assets/27390798/25039991/b766c954-2141-11e7-9b0b-aa757b4a4e25.png)


Most of the time I am using IE11 when replicating.

For the HTML template, I'm still going to ask our client if it's okay to disclose it since its confidential.

**Comment by danielfernandez** [comment] 2017-04-14 09:53
> Based on the response from server, there is no additional markup at all not even the </script> closing tag.

OK, if it is so, it is quite strange that this is an issue related to JavaScript parsing. It might be your server closing the stream for some network-related reason, or even an exception happening during template processing for any other reason, and your browser just receiving the part of the output buffer that has already been committed towards the browser. Can you see any errors or warnings at the server log when this happens?

And if not, what about the "network" tab in the Developer tools, what status does it show for the connection that retrieves your HTML? do you see any errors or warning there issued by the browser?

> For the HTML template, I'm still going to ask our client if it's okay to disclose it since its confidential.

It doesn't have to be exactly the same template, as long as it replicates your issue. Maybe emulating the same structure and size/type of fragments is enough to replicate it.

**Comment by kiriljames** [comment] 2017-04-19 07:17
If server has the problem, it would be too much of a coincidence that it would always happen at the same location.

Unfortunately, when this happen, there is no warning/error log in the server. And also HTTP status is 200.

For html test template, please refer [https://www.dropbox.com/s/ulj3r20ih920vvw/test_template_html.zip?dl=0](url)

the code will stop at line 226 in test_header.html

**Comment by danielfernandez** [comment] 2017-04-19 08:46
Quick question: is the Jackson library (`jackson-databind`) included in your classpath? if so, what specific version?

**Comment by kiriljames** [comment] 2017-04-19 09:40
Yes, we are using `jackson-databind-2.7.5`

**Comment by danielfernandez** [comment] 2017-04-19 10:23
And are you using your own implementation of Thymeleaf's JavaScript serializer based on your own configuration of a Jackson ObjectMapper? have you got any kind of manual Jackson configuration?

**Comment by danielfernandez** [comment] 2017-04-19 22:41
OK, I know what is happening, but based on your explanations I still cannot understand why this is happening to you.

When Jackson is in the classpath, Thymeleaf uses it for the serialization of values in JavaScript inlining or `JAVASCRIPT` template mode (defaulting to an internal implementation if Jackson is not present).

And It's Jackson that's provoking your issue, not really Thymeleaf. After serializing *as JavaScript* the first object Thymeleaf asks Jackson to (in your case, that `currencyAll` variable), Jackson is **closing the output `Writer`**. Some `Writer` implementations like Tomcat's `CoyoteWriter`, when closed, simply ignore any further writings without any kind of exception or warning. Thus the `HTTP 200` and the strange behaviour of output being cut.

But note that this closing of the `Writer` is actually the normal, default behaviour in Jackson. Jackson does this unless you disable the `JsonGenerator.Feature.AUTO_CLOSE_TARGET` feature. But this is precisely what Thymeleaf does [here](https://github.com/thymeleaf/thymeleaf/blob/687ccb86e8ceb062ab96692d77d709074209604b/src/main/java/org/thymeleaf/standard/serializer/StandardJavaScriptSerializer.java#L151), since version `3.0.0.BETA02` (see #462). And Jackson's `ObjectMapper` objects are thread-safe as long as all initialisation is done before read/write operations start (which is the case), so it shouldn't be a concurrency issue.

Now, the problem is, I am unable to reproduce your issue with your template, using `3.0.5.RELEASE` or `3.0.3.RELEASE`. I've tried your specific version of Jackson just in case it was a Jackson bug for that specific version, but it's working OK for me too. The only way I had to confirm what was happening to you was to modify my local Thymeleaf code to comment out that line disabling Jackson's *autoclose*, then execute… and only then I obtained exactly the same result as you.

So right now I see three possibilities — there might be more, but as of now only these come to my head:

**1.** Maybe you are somehow using a mix of Thymeleaf versions, one of which is `3.0.0.BETA01`? For example, through a load balancer that balances load to several servers, one of which is not completely updated… this scenario would be consistent with the fact that this doesn't happen *always* for you…

**2.** Maybe you are not using a mix of Thymeleaf versions, but a mix of *Jackson* versions, and in some cases you end up executing a very, very old Jackson version that does not include support for disabling *autoclose*?

**3.** Maybe you have created your own implementation of Thymeleaf's `IStandardJavaScriptSerializer`? The JavaScript serializer is an extension point in Thymeleaf, so I'm thinking maybe you have fine-tuned JavaScript serialization and did not disable that Jackson feature?

Other than that, well… you could try updating Jackson and see if the error goes, just in case it indeed is a bug in that library and I simply haven't been lucky replicating it…

**Comment by kiriljames** [comment] 2017-04-20 09:31
Thank you very much for your help.

I also tried what you did by commenting the line that disabled the Jackson's _autoclose_ in my local thymeleaf code which I cloned from the repository and then I obtained exactly the same result as what I reported.

For the 3 scenarios:

1. I'm not sure about the load balancing part, since I can reproduce the issue in my localhost

2. I checked again but all version of Jackson are the same.

3. We don't have custom implementation for Thymeleaf's `IStandardJavaScriptSerializer`. It might be nicer if this is the case and we just need to disable the Jackson feature.

For now, I will just try to update my Jackson and hopefully it will solve the problem.

**Comment by danielfernandez** [comment] 2017-04-24 13:36
Did the Jackson upgrade have any effects?

**Comment by danielfernandez** [comment] 2017-04-24 23:28
As an additional note, I've tried your template in a custom-made application with `jackson-databind` 2.7.5, started a Tomcat with it, and used 3 concurrent `curl`-based scripts performing 5,000 requests each in order to try to reproduce the issue. Nothing. All requests were served alright and Jackson seemed not to ever close the `Writer` when it should not.

I'm wondering… would it be possible for you to create a *test project* instead of just a test template? Something I could directly run in order to try to reproduce it locally and debug what is actually happening to you?

**Comment by kiriljames** [comment] 2017-04-25 02:18
Sorry for the late feedback.

Yes, unfortunately I can still reproduce the issue while using the latest version of Jackson lib.
I also find it strange that I cannot reproduce the issue using curl command. But I'm also sure its not browser issue since all browser can reproduce it.

For test project, I will try to create.

**Comment by danielfernandez** [comment] 2017-05-03 11:24
Any news on this? were you able to create a separate project that reproduces the issue?

**Comment by kiriljames** [comment] 2017-05-09 01:09
Sorry for the late feedback, I was on a vacation.
As of the moment, the project I created was not able to reproduce the issue yet.
I'll keep you updated.

**Comment by kiriljames** [comment] 2017-05-12 01:20
Unfortunately, I couldn't reproduce the issue using the test project I created.

**Comment by danielfernandez** [comment] 2017-05-13 13:42
That's very unfortunate. I'm thinking, perhaps there are any other parts of your failing application where you customise Jackson's global behaviour somehow, or apply to it (to Jackson) any extension points that might provoke it closing these `Writer`s when it has been instructed not to?

**Comment by kiriljames** [comment] 2017-05-15 03:06
We have `JsonUtil` that uses jackson library.

Below is how we initialized the `ObjectMapper `:

    public final class JsonUtil {

        private static JsonFactory jsonFactory = null;
        private static ObjectMapper objectMapper = null;

        static{
            jsonFactory = new JsonFactory();
            objectMapper = new ObjectMapper();
            objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
            objectMapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false);
            objectMapper.setSerializationInclusion(Include.NON_NULL);
        }
       ...
    }

This util is only used inside our web-socket code.
I also tried disabling the Jackson's auto close feature but no effect at all.

I'm not sure if this would have an impact on the issue.

**Comment by danielfernandez** [comment] 2017-06-10 11:09
Still unable to reproduce this. I was wondering, as a last-resort idea… maybe you are using any Jackson extensions (for serialising specific data types or similar) that might have a bug and be closing your output stream only when they run (e.g. when your data contains a field of a specific data type)? Maybe that's the reason you cannot reproduce it in a test application, because it depends on the specific data being serialised…

**Comment by danielfernandez** [comment] 2017-07-27 19:52
I'm closing this for now as *cannot reproduce* as it's been two months and a half since you last reported details on this issue, and this is still not reproducible on our side. Please don't hesitate reopening it at any moment if you are able to obtain any further detail on how this could be reproduced and/or diagnosed. Thanks.

**Closed as completed by danielfernandez** 2017-07-27 19:52 UTC
Labels: tracker:question
