### ISSUE TITLE
JavaScript line comment (//) parsing breaks when EOF comes before \n

### ISSUE THREAD

**Issue by AstatorDem** [thymeleaf/thymeleaf#615] opened 2017-05-15 08:44 UTC
Since upgrading to `3.0.6.RELEASE`, any script code wrapped around <![CDATA[ ]]> will give a parser error:
```html
<script type="application/javascript" th:inline="javascript">
//<![CDATA[
...code...
//]]>
</script>
```
Error:
```java
Caused by: org.thymeleaf.templateparser.text.TextParseException: (Line = 40, Column = 5) Incomplete structure: "//]]>"
```
This worked fine in `3.0.5.RELEASE`.
Probably related to #589, as I can confirm that wrapping it around `/*...*/` fixes the issue.

**Comment by danielfernandez** [comment] 2017-05-15 23:12
I am not able to reproduce this. Perhaps it doesn't happen with any script wrapped with `CDATA`, but it depends on something else...

Could you please provide a specific example of a complete `<script>` block that produces this error for you?

**Comment by AstatorDem** [comment] 2017-05-16 08:33
An update on the issue:
I've managed to find a way to reproduce the error all the time.
This html compiles fine:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:th="http://www.thymeleaf.org">
<head>
  <meta charset="UTF-8">
  <title>TEST</title>
</head>
<body>
<h1>Hello!</h1>
<script type="text/javascript" th:inline="javascript">
//Im a comment!
</script>
<script type="application/javascript" th:src="@{/js/example.js}"></script>
</body>
</html>
```
example.js:
```javascript
//Im a comment!
This is an empty line.
```
Any of these give a parser error:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:th="http://www.thymeleaf.org">
<head>
  <meta charset="UTF-8">
  <title>TEST</title>
</head>
<body>
<h1>Hello!</h1>
<script type="text/javascript" th:inline="javascript">
//I m a comment!</script>
<script type="application/javascript" th:src="@{/js/example.js}"></script>
</body>
</html>
```
example.js:
```javascript
//Im a comment!
```

**Comment by danielfernandez** [comment] 2017-05-20 23:14
This is confirmed as a bug. The problem is that JS line comments (`//...`) don't have a finishing structure other than `\n` or `EOF`, and it is precisely `EOF` that is not being correctly handled. When the script ends with a line comment open, it thinks there is an open structure that still hasn't had its corresponding closing and it fails.

**Closed as completed** 2017-06-05 21:54 UTC
Labels: tracker:problem, status:solved

**Comment by danielfernandez** [comment] 2017-06-05 21:59
Already in `3.0.7-SNAPSHOT`
